//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace huhu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_all
    {
        public string admin_id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string password { get; set; }
        public int power { get; set; }
        public int audit_status { get; set; }
        public string update_time { get; set; }
        public string register_time { get; set; }
    }
}
