//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace huhu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class advert_all
    {
        public string advert_id { get; set; }
        public string title { get; set; }
        public string brief { get; set; }
        public string content { get; set; }
        public string picture { get; set; }
        public int advert_type { get; set; }
        public int rank { get; set; }
        public string start_time { get; set; }
        public string end_time { get; set; }
        public long audit_status { get; set; }
        public string mtime { get; set; }
        public string ctime { get; set; }
    }
}
