//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace huhu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class article_reply
    {
        public string reply_id { get; set; }
        public string article_id { get; set; }
        public string user_id { get; set; }
        public string reply_comment_id { get; set; }
        public string reply_content { get; set; }
        public string reply_to_reply_id { get; set; }
        public string reply_to_user_id { get; set; }
        public int reply_type { get; set; }
        public int reply_status { get; set; }
        public string ctime { get; set; }
    }
}
