//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace huhu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class article_all
    {
        public string article_id { get; set; }
        public string user_id { get; set; }
        public string cover_image { get; set; }
        public string title { get; set; }
        public string brief_content { get; set; }
        public string mark_content { get; set; }
        public string tag_ids { get; set; }
        public string edit_type { get; set; }
        public int audit_status { get; set; }
        public string mtime { get; set; }
        public string ctime { get; set; }
    }
}
