//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace huhu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public string log_id { get; set; }
        public string controller_name { get; set; }
        public string action_name { get; set; }
        public string action_param { get; set; }
        public string http_header { get; set; }
        public string client_ip { get; set; }
        public string client_type { get; set; }
        public string http_method { get; set; }
        public string exception { get; set; }
        public string attack_time { get; set; }
    }
}
