//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace huhu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_all
    {
        public string report_id { get; set; }
        public string article_id { get; set; }
        public string issue { get; set; }
        public string prove_pic { get; set; }
        public string describe { get; set; }
        public string ctime { get; set; }
    }
}
