//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace huhu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class topic_all
    {
        public string topic_id { get; set; }
        public string user_id { get; set; }
        public string topic_circle_id { get; set; }
        public string content { get; set; }
        public string pic_list { get; set; }
        public string url { get; set; }
        public string topic { get; set; }
        public int status { get; set; }
        public string mtime { get; set; }
        public string ctime { get; set; }
    }
}
