//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace huhu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_collect
    {
        public string id { get; set; }
        public string user_id { get; set; }
        public string collection_id { get; set; }
        public string item_id { get; set; }
        public string ctime { get; set; }
    }
}
