//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace huhu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_all
    {
        public string user_id { get; set; }
        public string user_name { get; set; }
        public string avatar_large { get; set; }
        public int level { get; set; }
        public string password { get; set; }
        public string phone { get; set; }
        public int phone_verified { get; set; }
        public string email { get; set; }
        public int email_verified { get; set; }
        public string qq_openid { get; set; }
        public string qq_nickname { get; set; }
        public string qq_figureurl { get; set; }
        public int qq_verified { get; set; }
        public string wechat_nickname { get; set; }
        public int wechat_verified { get; set; }
        public string weibo_nickname { get; set; }
        public int weibo_verified { get; set; }
        public string job_title { get; set; }
        public string ip_address { get; set; }
        public string place { get; set; }
        public int status { get; set; }
        public string update_time { get; set; }
        public string register_time { get; set; }
    }
}
